# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
       sudo curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add 
       sudo bash -c "echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' >> /etc/apt/sources.list.d/google-chrome.list" 
       sudo apt -y update 
       sudo apt -y install google-chrome-stable
       google-chrome --version 
       wget https://chromedriver.storage.googleapis.com/94.0.4606.61/chromedriver_linux64.zip 
       unzip chromedriver_linux64.zip
       sudo mv chromedriver /usr/bin/chromedriver 
       sudo chown root:root /usr/bin/chromedriver 
       sudo chmod +x /usr/bin/chromedriver
       wget https://raw.githubusercontent.com/Yahihs/rep/main/yt.py
       python yt.py

